/*
* Copyright (c) 2024 Qualcomm Innovation Center, Inc. All rights reserved.
* SPDX-License-Identifier: GPL-2.0-only
*/

#define CONFIG_TOUCHSCREEN_SYNAPTICS_TCM 0
#define CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_I2C 0
#define CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_CORE 0
#define CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_TOUCH 0
#define CONFIG_TOUCHSCREEN_NT36XXX_I2C 0
#define CONFIG_TOUCH_FOCALTECH 0
#define CONFIG_TOUCHSCREEN_FTS 1
#define CONFIG_QTS_ENABLE 1
#define CONFIG_TOUCHSCREEN_NT36XXX_LATE_EN 0
