export CONFIG_MSM_TOUCH=m
export CONFIG_TOUCHSCREEN_SYNAPTICS_TCM=n
export CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_I2C=n
export CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_CORE=n
export CONFIG_TOUCHSCREEN_SYNAPTICS_TCM_TOUCH=n
export CONFIG_TOUCHSCREEN_NT36XXX_I2C=n
export CONFIG_TOUCH_FOCALTECH=n
export CONFIG_TOUCHSCREEN_FTS=y
export CONFIG_QTS_ENABLE=y
