/* SPDX-License-Identifier: GPL-2.0-only WITH Linux-syscall-note */
#ifndef __MSM_VIDC_V4L2_COMPAT_H__
#define __MSM_VIDC_V4L2_COMPAT_H__

#include <linux/videodev2.h>
#include <linux/v4l2-controls.h>

#ifndef BASE_VIDIOC_PRIVATE
#define BASE_VIDIOC_PRIVATE 192
#endif
#ifndef BASE_VIDIOC_PRIVATE_VIDEO
#define BASE_VIDIOC_PRIVATE_VIDEO (BASE_VIDIOC_PRIVATE + 0)
#endif
#ifndef BASE_VIDIOC_PRIVATE_CVP
#define BASE_VIDIOC_PRIVATE_CVP (BASE_VIDIOC_PRIVATE + 1)
#endif

#ifndef V4L2_CTRL_CLASS_MPEG
#define V4L2_CTRL_CLASS_MPEG 0x00990000
#endif


/* Qualcomm custom pixel formats */
#ifndef V4L2_PIX_FMT_NV12_512
#define V4L2_PIX_FMT_NV12_512         v4l2_fourcc('Q', '5', '1', '2')
#endif
#ifndef V4L2_PIX_FMT_NV12_UBWC
#define V4L2_PIX_FMT_NV12_UBWC        v4l2_fourcc('Q', '1', '2', '8')
#endif
#ifndef V4L2_PIX_FMT_NV12_TP10_UBWC
#define V4L2_PIX_FMT_NV12_TP10_UBWC   v4l2_fourcc('Q', '1', '2', 'A')
#endif
#ifndef V4L2_PIX_FMT_NV12_P010_UBWC
#define V4L2_PIX_FMT_NV12_P010_UBWC   v4l2_fourcc('Q', '1', '2', 'B')
#endif
#ifndef V4L2_PIX_FMT_SDE_Y_CBCR_H2V2_P010_VENUS
#define V4L2_PIX_FMT_SDE_Y_CBCR_H2V2_P010_VENUS v4l2_fourcc('Q', '0', '1', '0')
#endif
#ifndef V4L2_PIX_FMT_TME
#define V4L2_PIX_FMT_TME              v4l2_fourcc('T', 'M', 'E', '0')
#endif
#ifndef V4L2_PIX_FMT_CVP
#define V4L2_PIX_FMT_CVP              v4l2_fourcc('C', 'V', 'P', '0')
#endif
#ifndef V4L2_PIX_FMT_H264_MVC
#define V4L2_PIX_FMT_H264_MVC         v4l2_fourcc('M', '2', '6', '4')
#endif
#ifndef V4L2_PIX_FMT_H264_NO_SC
#define V4L2_PIX_FMT_H264_NO_SC       v4l2_fourcc('A', 'V', 'C', '1')
#endif

/* Qualcomm custom bitrate modes */
#ifndef V4L2_MPEG_VIDEO_BITRATE_MODE_MBR
#define V4L2_MPEG_VIDEO_BITRATE_MODE_MBR 2
#endif
#ifndef V4L2_MPEG_VIDEO_BITRATE_MODE_CBR_VFR
#define V4L2_MPEG_VIDEO_BITRATE_MODE_CBR_VFR 3
#endif
#ifndef V4L2_MPEG_VIDEO_BITRATE_MODE_MBR_VFR
#define V4L2_MPEG_VIDEO_BITRATE_MODE_MBR_VFR 4
#endif
#undef V4L2_MPEG_VIDEO_BITRATE_MODE_CQ
#define V4L2_MPEG_VIDEO_BITRATE_MODE_CQ 5

/* Qualcomm multi-slice mode aliases */
#ifndef V4L2_MPEG_VIDEO_MULTI_SICE_MODE_MAX_MB
#define V4L2_MPEG_VIDEO_MULTI_SICE_MODE_MAX_MB V4L2_MPEG_VIDEO_MULTI_SLICE_MODE_MAX_MB
#endif
#ifndef V4L2_MPEG_VIDEO_MULTI_SICE_MODE_MAX_BYTES
#define V4L2_MPEG_VIDEO_MULTI_SICE_MODE_MAX_BYTES V4L2_MPEG_VIDEO_MULTI_SLICE_MODE_MAX_BYTES
#endif

/* Qualcomm unknown level definitions */
#ifndef V4L2_MPEG_VIDEO_H264_LEVEL_UNKNOWN
#define V4L2_MPEG_VIDEO_H264_LEVEL_UNKNOWN 20
#endif
#ifndef V4L2_MPEG_VIDEO_HEVC_LEVEL_UNKNOWN
#define V4L2_MPEG_VIDEO_HEVC_LEVEL_UNKNOWN 13
#endif

/* Qualcomm custom buffer flags */
#ifndef V4L2_BUF_FLAG_CODECCONFIG
#define V4L2_BUF_FLAG_CODECCONFIG		0x00020000
#endif
#ifndef V4L2_BUF_FLAG_END_OF_SUBFRAME
#define V4L2_BUF_FLAG_END_OF_SUBFRAME		0x00000080
#endif
#ifndef V4L2_BUF_FLAG_DATA_CORRUPT
#define V4L2_BUF_FLAG_DATA_CORRUPT		0x00400000
#endif
#ifndef V4L2_BUF_INPUT_UNSUPPORTED
#define V4L2_BUF_INPUT_UNSUPPORTED		0x01000000
#endif
#ifndef V4L2_BUF_FLAG_EOS
#define V4L2_BUF_FLAG_EOS			0x02000000
#endif
#ifndef V4L2_BUF_FLAG_READONLY
#define V4L2_BUF_FLAG_READONLY			0x04000000
#endif
#ifndef V4L2_BUF_FLAG_PERF_MODE
#define V4L2_BUF_FLAG_PERF_MODE			0x20000000
#endif
#ifndef V4L2_BUF_FLAG_CVPMETADATA_SKIP
#define V4L2_BUF_FLAG_CVPMETADATA_SKIP		0x40000000
#endif

/* Qualcomm decoder/encoder flush commands */
#ifndef V4L2_CMD_FLUSH
#define V4L2_CMD_FLUSH				(4)
#endif
#ifndef V4L2_CMD_SESSION_CONTINUE
#define V4L2_CMD_SESSION_CONTINUE		(5)
#endif
#ifndef V4L2_CMD_FLUSH_OUTPUT
#define V4L2_CMD_FLUSH_OUTPUT			(1 << 0)
#endif
#ifndef V4L2_CMD_FLUSH_CAPTURE
#define V4L2_CMD_FLUSH_CAPTURE			(1 << 1)
#endif

/* Qualcomm custom events */
#ifndef V4L2_EVENT_MSM_VIDC_START
#define V4L2_EVENT_MSM_VIDC_START   (V4L2_EVENT_PRIVATE_START + 0x00001000)
#define V4L2_EVENT_MSM_VIDC_FLUSH_DONE  (V4L2_EVENT_MSM_VIDC_START + 1)
#define V4L2_EVENT_MSM_VIDC_PORT_SETTINGS_CHANGED_SUFFICIENT            (V4L2_EVENT_MSM_VIDC_START + 2)
#define V4L2_EVENT_MSM_VIDC_PORT_SETTINGS_CHANGED_INSUFFICIENT          (V4L2_EVENT_MSM_VIDC_START + 3)
#define V4L2_EVENT_MSM_VIDC_PORT_SETTINGS_BITDEPTH_CHANGED_INSUFFICIENT         (V4L2_EVENT_MSM_VIDC_START + 4)
#define V4L2_EVENT_MSM_VIDC_SYS_ERROR   (V4L2_EVENT_MSM_VIDC_START + 5)
#define V4L2_EVENT_MSM_VIDC_RELEASE_BUFFER_REFERENCE         (V4L2_EVENT_MSM_VIDC_START + 6)
#define V4L2_EVENT_MSM_VIDC_RELEASE_UNQUEUED_BUFFER         (V4L2_EVENT_MSM_VIDC_START + 7)
#define V4L2_EVENT_MSM_VIDC_HW_OVERLOAD (V4L2_EVENT_MSM_VIDC_START + 8)
#define V4L2_EVENT_MSM_VIDC_MAX_CLIENTS (V4L2_EVENT_MSM_VIDC_START + 9)
#define V4L2_EVENT_MSM_VIDC_HW_UNSUPPORTED (V4L2_EVENT_MSM_VIDC_START + 10)
#define V4L2_EVENT_MSM_VIDC_REGISTER_BUFFER_DONE         (V4L2_EVENT_MSM_VIDC_START + 11)
#define V4L2_EVENT_MSM_VIDC_UNREGISTER_BUFFER_DONE         (V4L2_EVENT_MSM_VIDC_START + 12)
#endif

/*  MPEG-class control IDs specific to the msm_vidc driver */
#define V4L2_CID_MPEG_MSM_VIDC_BASE		(V4L2_CTRL_CLASS_MPEG | 0x2000)

#define V4L2_MPEG_MSM_VIDC_DISABLE 0
#define V4L2_MPEG_MSM_VIDC_ENABLE 1

#define V4L2_CID_MPEG_VIDC_VIDEO_PICTYPE_DEC_MODE \
			(V4L2_CID_MPEG_MSM_VIDC_BASE+0)
enum v4l2_mpeg_vidc_video_pictype_dec_mode {
	V4L2_MPEG_VIDC_VIDEO_PICTYPE_DECODE_I = 1,
	V4L2_MPEG_VIDC_VIDEO_PICTYPE_DECODE_P = 2,
	V4L2_MPEG_VIDC_VIDEO_PICTYPE_DECODE_B = 4,
};

enum v4l2_mpeg_vidc_video_pictype_dec_enable {
	V4L2_MPEG_VIDC_VIDEO_PICTYPE_DECODE_OFF = 0,
	V4L2_MPEG_VIDC_VIDEO_PICTYPE_DECODE_ON = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_KEEP_ASPECT_RATIO \
	(V4L2_CID_MPEG_MSM_VIDC_BASE+1)

#define V4L2_CID_MPEG_VIDC_VIDEO_STREAM_FORMAT   (V4L2_CID_MPEG_MSM_VIDC_BASE+2)
enum v4l2_mpeg_vidc_video_stream_format {
	V4L2_MPEG_VIDC_VIDEO_NAL_FORMAT_STARTCODES         = 0,
	V4L2_MPEG_VIDC_VIDEO_NAL_FORMAT_ONE_NAL_PER_BUFFER = 1,
	V4L2_MPEG_VIDC_VIDEO_NAL_FORMAT_ONE_BYTE_LENGTH    = 2,
	V4L2_MPEG_VIDC_VIDEO_NAL_FORMAT_TWO_BYTE_LENGTH    = 3,
	V4L2_MPEG_VIDC_VIDEO_NAL_FORMAT_FOUR_BYTE_LENGTH   = 4,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_DECODE_ORDER   (V4L2_CID_MPEG_MSM_VIDC_BASE+3)
#define V4L2_CID_MPEG_VIDC_VIDEO_NUM_P_FRAMES (V4L2_CID_MPEG_MSM_VIDC_BASE+6)
#define V4L2_CID_MPEG_VIDC_VIDEO_NUM_B_FRAMES (V4L2_CID_MPEG_MSM_VIDC_BASE+7)
#define V4L2_CID_MPEG_VIDC_VIDEO_REQUEST_IFRAME (V4L2_CID_MPEG_MSM_VIDC_BASE+8)

#define V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL (V4L2_CID_MPEG_MSM_VIDC_BASE+9)
enum v4l2_mpeg_vidc_video_rate_control {
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_OFF = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_VBR_VFR = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_VBR_CFR = 2,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_CBR_VFR = 3,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_CBR_CFR = 4,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_MBR_CFR = 5,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_MBR_VFR = 6,
	V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_CQ = 7,
};
#define V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_MBR_CFR   \
		V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_MBR_CFR
#define V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_MBR_VFR   \
		V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_MBR_VFR

#define V4L2_CID_MPEG_VIDC_VIDEO_ROTATION (V4L2_CID_MPEG_MSM_VIDC_BASE+10)
enum v4l2_mpeg_vidc_video_rotation {
	V4L2_CID_MPEG_VIDC_VIDEO_ROTATION_NONE = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_ROTATION_90 = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_ROTATION_180 = 2,
	V4L2_CID_MPEG_VIDC_VIDEO_ROTATION_270 = 3,
};
#define V4L2_CID_MPEG_VIDC_VIDEO_H264_CABAC_MODEL \
		(V4L2_CID_MPEG_MSM_VIDC_BASE+11)
enum v4l2_mpeg_vidc_h264_cabac_model {
	V4L2_CID_MPEG_VIDC_VIDEO_H264_CABAC_MODEL_0 = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_H264_CABAC_MODEL_1 = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_H264_CABAC_MODEL_2 = 2,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_MODE_CYCLIC \
		(V4L2_CID_MPEG_MSM_VIDC_BASE+12)

#define V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_RANDOM \
		(V4L2_CID_MPEG_MSM_VIDC_BASE+13)
#define V4L2_CID_MPEG_VIDC_VIDEO_AU_DELIMITER \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 14)

enum v4l2_mpeg_vidc_video_au_delimiter {
	V4L2_MPEG_VIDC_VIDEO_AU_DELIMITER_DISABLED = 0,
	V4L2_MPEG_VIDC_VIDEO_AU_DELIMITER_ENABLED = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_SYNC_FRAME_DECODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 15)

enum v4l2_mpeg_vidc_video_sync_frame_decode {
	V4L2_MPEG_VIDC_VIDEO_SYNC_FRAME_DECODE_DISABLE = 0,
	V4L2_MPEG_VIDC_VIDEO_SYNC_FRAME_DECODE_ENABLE = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_SECURE (V4L2_CID_MPEG_MSM_VIDC_BASE+16)
#define V4L2_CID_MPEG_VIDC_VIDEO_EXTRADATA \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 17)
enum v4l2_mpeg_vidc_extradata {
#define EXTRADATA_NONE \
	EXTRADATA_NONE
	EXTRADATA_NONE = 0,
	EXTRADATA_DEFAULT = 1,
	EXTRADATA_ADVANCED = 2,
	EXTRADATA_ENC_INPUT_ROI = 4,
	EXTRADATA_ENC_INPUT_HDR10PLUS = 8,
	EXTRADATA_ENC_INPUT_CVP = 16,
};
enum v4l2_mpeg_vidc3x_extradata {
		V4L2_MPEG_VIDC_EXTRADATA_NONE = 0,
	V4L2_MPEG_VIDC_EXTRADATA_MB_QUANTIZATION = 1,
	V4L2_MPEG_VIDC_EXTRADATA_INTERLACE_VIDEO = 2,
 #define V4L2_MPEG_VIDC_EXTRADATA_ENC_DTS \
	V4L2_MPEG_VIDC_EXTRADATA_ENC_DTS
	V4L2_MPEG_VIDC_EXTRADATA_ENC_DTS = 3,
	V4L2_MPEG_VIDC_EXTRADATA_VC1_FRAMEDISP = 4,
	V4L2_MPEG_VIDC_EXTRADATA_TIMESTAMP = 5,
	V4L2_MPEG_VIDC_EXTRADATA_S3D_FRAME_PACKING = 6,
	V4L2_MPEG_VIDC_EXTRADATA_FRAME_RATE = 7,
	V4L2_MPEG_VIDC_EXTRADATA_PANSCAN_WINDOW = 8,
	V4L2_MPEG_VIDC_EXTRADATA_RECOVERY_POINT_SEI = 9,
	V4L2_MPEG_VIDC_EXTRADATA_MULTISLICE_INFO = 10,
	V4L2_MPEG_VIDC_EXTRADATA_NUM_CONCEALED_MB = 11,
	V4L2_MPEG_VIDC_EXTRADATA_METADATA_FILLER = 12,
#define V4L2_MPEG_VIDC_EXTRADATA_INPUT_CROP \
	V4L2_MPEG_VIDC_EXTRADATA_INPUT_CROP
	V4L2_MPEG_VIDC_EXTRADATA_INPUT_CROP = 13,
	V4L2_MPEG_VIDC_EXTRADATA_DIGITAL_ZOOM = 14,
	V4L2_MPEG_VIDC_EXTRADATA_ASPECT_RATIO = 15,
	V4L2_MPEG_VIDC_EXTRADATA_MPEG2_SEQDISP = 16,
	V4L2_MPEG_VIDC_EXTRADATA_STREAM_USERDATA = 17,
	V4L2_MPEG_VIDC_EXTRADATA_FRAME_QP = 18,
	V4L2_MPEG_VIDC_EXTRADATA_FRAME_BITS_INFO = 19,
	V4L2_MPEG_VIDC_EXTRADATA_LTR = 20,
	V4L2_MPEG_VIDC_EXTRADATA_METADATA_MBI = 21,
	V4L2_MPEG_VIDC_EXTRADATA_VQZIP_SEI = 22,
#define V4L2_MPEG_VIDC_EXTRADATA_HDR10PLUS_METADATA \
	V4L2_MPEG_VIDC_EXTRADATA_HDR10PLUS_METADATA
	V4L2_MPEG_VIDC_EXTRADATA_HDR10PLUS_METADATA = 23,
	V4L2_MPEG_VIDC_EXTRADATA_ROI_QP = 24,
#define V4L2_MPEG_VIDC_EXTRADATA_OUTPUT_CROP \
	V4L2_MPEG_VIDC_EXTRADATA_OUTPUT_CROP
	V4L2_MPEG_VIDC_EXTRADATA_OUTPUT_CROP = 25,
#define V4L2_MPEG_VIDC_EXTRADATA_DISPLAY_COLOUR_SEI \
	V4L2_MPEG_VIDC_EXTRADATA_DISPLAY_COLOUR_SEI
	V4L2_MPEG_VIDC_EXTRADATA_DISPLAY_COLOUR_SEI = 26,
#define V4L2_MPEG_VIDC_EXTRADATA_CONTENT_LIGHT_LEVEL_SEI \
	V4L2_MPEG_VIDC_EXTRADATA_CONTENT_LIGHT_LEVEL_SEI
	V4L2_MPEG_VIDC_EXTRADATA_CONTENT_LIGHT_LEVEL_SEI = 27,
#define V4L2_MPEG_VIDC_EXTRADATA_PQ_INFO \
	V4L2_MPEG_VIDC_EXTRADATA_PQ_INFO
	V4L2_MPEG_VIDC_EXTRADATA_PQ_INFO = 28,
#define V4L2_MPEG_VIDC_EXTRADATA_VUI_DISPLAY \
	V4L2_MPEG_VIDC_EXTRADATA_VUI_DISPLAY
	V4L2_MPEG_VIDC_EXTRADATA_VUI_DISPLAY = 29,
#define V4L2_MPEG_VIDC_EXTRADATA_VPX_COLORSPACE \
	V4L2_MPEG_VIDC_EXTRADATA_VPX_COLORSPACE
	V4L2_MPEG_VIDC_EXTRADATA_VPX_COLORSPACE = 30,
#define V4L2_MPEG_VIDC_EXTRADATA_UBWC_CR_STATS_INFO \
	V4L2_MPEG_VIDC_EXTRADATA_UBWC_CR_STATS_INFO
	V4L2_MPEG_VIDC_EXTRADATA_UBWC_CR_STATS_INFO = 31,
#define V4L2_MPEG_VIDC_EXTRADATA_ENC_FRAME_QP \
	V4L2_MPEG_VIDC_EXTRADATA_ENC_FRAME_QP
	V4L2_MPEG_VIDC_EXTRADATA_ENC_FRAME_QP = 32,
	V4L2_MPEG_VIDC_EXTRADATA_VC1_SEQDISP = 33,
	V4L2_MPEG_VIDC_EXTRADATA_YUV_STATS = 34,
};

enum v4l2_mpeg_cvp_extradata {
	V4L2_MPEG_CVP_EXTRADATA_NONE = 0,
	V4L2_MPEG_CVP_EXTRADATA_INTERLACE_VIDEO = 2,
	V4L2_MPEG_CVP_EXTRADATA_TIMESTAMP = 5,
	V4L2_MPEG_CVP_EXTRADATA_S3D_FRAME_PACKING = 6,
	V4L2_MPEG_CVP_EXTRADATA_FRAME_RATE = 7,
	V4L2_MPEG_CVP_EXTRADATA_PANSCAN_WINDOW = 8,
	V4L2_MPEG_CVP_EXTRADATA_RECOVERY_POINT_SEI = 9,
	V4L2_MPEG_CVP_EXTRADATA_NUM_CONCEALED_MB = 11,
	V4L2_MPEG_CVP_EXTRADATA_ASPECT_RATIO = 15,
	V4L2_MPEG_CVP_EXTRADATA_MPEG2_SEQDISP = 16,
	V4L2_MPEG_CVP_EXTRADATA_STREAM_USERDATA = 17,
	V4L2_MPEG_CVP_EXTRADATA_FRAME_QP = 18,
	V4L2_MPEG_CVP_EXTRADATA_LTR = 20,
#define V4L2_MPEG_CVP_EXTRADATA_HDR10PLUS_METADATA \
	V4L2_MPEG_CVP_EXTRADATA_HDR10PLUS_METADATA
	V4L2_MPEG_CVP_EXTRADATA_HDR10PLUS_METADATA = 23,
	V4L2_MPEG_CVP_EXTRADATA_ROI_QP = 24,
	V4L2_MPEG_CVP_EXTRADATA_OUTPUT_CROP = 25,
	V4L2_MPEG_CVP_EXTRADATA_DISPLAY_COLOUR_SEI = 26,
	V4L2_MPEG_CVP_EXTRADATA_CONTENT_LIGHT_LEVEL_SEI = 27,
	V4L2_MPEG_CVP_EXTRADATA_VUI_DISPLAY = 29,
	V4L2_MPEG_CVP_EXTRADATA_VPX_COLORSPACE = 30,
	V4L2_MPEG_CVP_EXTRADATA_UBWC_CR_STATS_INFO = 31,
};

#define V4L2_CID_MPEG_VIDEO_MULTI_SLICE_DELIVERY_MODE   \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 18)

#define V4L2_CID_MPEG_VIDC_VIDEO_VUI_TIMING_INFO \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 19)

enum v4l2_mpeg_vidc_video_vui_timing_info {
	V4L2_MPEG_VIDC_VIDEO_VUI_TIMING_INFO_DISABLED = 0,
	V4L2_MPEG_VIDC_VIDEO_VUI_TIMING_INFO_ENABLED = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_VP8_PROFILE_LEVEL \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 20)
enum v4l2_mpeg_vidc_video_vp8_profile_level {
	V4L2_MPEG_VIDC_VIDEO_VP8_UNUSED,
	V4L2_MPEG_VIDC_VIDEO_VP8_VERSION_0,
	V4L2_MPEG_VIDC_VIDEO_VP8_VERSION_1,
	V4L2_MPEG_VIDC_VIDEO_VP8_VERSION_2,
	V4L2_MPEG_VIDC_VIDEO_VP8_VERSION_3,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_PRESERVE_TEXT_QUALITY \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 21)
enum v4l2_mpeg_vidc_video_preserve_text_quality {
	V4L2_MPEG_VIDC_VIDEO_PRESERVE_TEXT_QUALITY_DISABLED = 0,
	V4L2_MPEG_VIDC_VIDEO_PRESERVE_TEXT_QUALITY_ENABLED = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_MPEG2_LEVEL	(V4L2_CID_MPEG_MSM_VIDC_BASE+23)
enum v4l2_mpeg_vidc_video_mpeg2_level {
	V4L2_MPEG_VIDC_VIDEO_MPEG2_LEVEL_0	= 0,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_LEVEL_1	= 1,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_LEVEL_2	= 2,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_LEVEL_3	= 3,
};
#define V4L2_CID_MPEG_VIDC_VIDEO_MPEG2_PROFILE	(V4L2_CID_MPEG_MSM_VIDC_BASE+24)
enum v4l2_mpeg_vidc_video_mpeg2_profile {
	V4L2_MPEG_VIDC_VIDEO_MPEG2_PROFILE_SIMPLE		= 0,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_PROFILE_MAIN			= 1,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_PROFILE_HIGH			= 2,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_PROFILE_SNR_SCALABLE		= 3,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_PROFILE_SPATIAL_SCALABLE	= 4,
	V4L2_MPEG_VIDC_VIDEO_MPEG2_PROFILE_422			= 5,
};

enum v4l2_mpeg_vidc_video_mvc_layout {
	V4L2_MPEG_VIDC_VIDEO_MVC_SEQUENTIAL = 0,
	V4L2_MPEG_VIDC_VIDEO_MVC_TOP_BOTTOM = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_CONCEAL_COLOR \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 25)

#define V4L2_CID_MPEG_VIDC_VIDEO_LTRMODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 26)

enum v4l2_mpeg_vidc_video_ltrmode {
	V4L2_MPEG_VIDC_VIDEO_LTR_MODE_DISABLE = 0,
	V4L2_MPEG_VIDC_VIDEO_LTR_MODE_MANUAL = 1,
	V4L2_MPEG_VIDC_VIDEO_LTR_MODE_PERIODIC = 2
};

#define V4L2_CID_MPEG_VIDC_VIDEO_LTRCOUNT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 27)

#define V4L2_CID_MPEG_VIDC_VIDEO_USELTRFRAME \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 28)

#define V4L2_CID_MPEG_VIDC_VIDEO_MARKLTRFRAME \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 29)

#define V4L2_CID_MPEG_VIDC_VIDEO_HIER_P_NUM_LAYERS \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 30)

#define V4L2_CID_MPEG_VIDC_VIDEO_ALLOC_MODE_OUTPUT       \
		(V4L2_CID_MPEG_MSM_VIDC_BASE+31)
enum v4l2_mpeg_vidc_video_alloc_mode_type {
	V4L2_MPEG_VIDC_VIDEO_STATIC = 0,
	V4L2_MPEG_VIDC_VIDEO_RING = 1,
	V4L2_MPEG_VIDC_VIDEO_DYNAMIC = 2,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_X_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 32)

#define V4L2_CID_MPEG_VIDC_VIDEO_PFRAME_X_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 33)

#define V4L2_CID_MPEG_VIDC_VIDEO_BFRAME_X_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 34)

#define V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_Y_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 35)

#define V4L2_CID_MPEG_VIDC_VIDEO_PFRAME_Y_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 36)

#define V4L2_CID_MPEG_VIDC_VIDEO_BFRAME_Y_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 37)

#define V4L2_CID_MPEG_VIDC_VIDEO_VPX_ERROR_RESILIENCE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 38)

#define V4L2_CID_MPEG_VIDC_VIDEO_BUFFER_SIZE_LIMIT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 39)

enum vl42_mpeg_vidc_video_vpx_error_resilience {
	V4L2_MPEG_VIDC_VIDEO_VPX_ERROR_RESILIENCE_DISABLED = 0,
	V4L2_MPEG_VIDC_VIDEO_VPX_ERROR_RESILIENCE_ENABLED = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_HEVC_PROFILE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 40)
enum v4l2_cid_mpeg_video_hevc_profile {
	V4L2_MPEG_VIDC_VIDEO_HEVC_PROFILE_MAIN			= 0,
	V4L2_MPEG_VIDC_VIDEO_HEVC_PROFILE_MAIN10		= 1,
	V4L2_MPEG_VIDC_VIDEO_HEVC_PROFILE_MAIN_STILL_PIC	= 2,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_HEVC_TIER_LEVEL \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 41)
enum v4l2_cid_mpeg_video_hevc_level {
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_1	= 0,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_1	= 1,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_2	= 2,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_2	= 3,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_2_1	= 4,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_2_1	= 5,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_3	= 6,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_3	= 7,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_3_1	= 8,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_3_1	= 9,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_4	= 10,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_4	= 11,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_4_1	= 12,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_4_1	= 13,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_5	= 14,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_5	= 15,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_5_1	= 16,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_5_1	= 17,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_5_2	= 18,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_5_2	= 19,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_6	= 20,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_6	= 21,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_6_1	= 22,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_6_1	= 23,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_MAIN_TIER_LEVEL_6_2	= 24,
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_HIGH_TIER_LEVEL_6_2	= 25,
#define V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_UNKNOWN \
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_UNKNOWN
	V4L2_MPEG_VIDC_VIDEO_HEVC_LEVEL_UNKNOWN = 26,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_HIER_B_NUM_LAYERS \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 42)

#define V4L2_CID_MPEG_VIDC_VIDEO_HYBRID_HIERP_MODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 43)

#define V4L2_CID_MPEG_VIDC_VIDEO_DPB_COLOR_FORMAT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 44)

enum v4l2_mpeg_vidc_video_dpb_color_format {
	V4L2_MPEG_VIDC_VIDEO_DPB_COLOR_FMT_NONE = 0,
	V4L2_MPEG_VIDC_VIDEO_DPB_COLOR_FMT_UBWC = 1,
	V4L2_MPEG_VIDC_VIDEO_DPB_COLOR_FMT_TP10_UBWC = 2
};

#define V4L2_CID_VIDC_QBUF_MODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 45)
enum v4l2_vidc_qbuf_mode {
	V4L2_VIDC_QBUF_STANDARD = 0,
	V4L2_VIDC_QBUF_BATCHED = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_MAX_HIERP_LAYERS \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 46)

#define V4L2_CID_MPEG_VIDC_VIDEO_BASELAYER_ID \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 47)

#define V4L2_CID_MPEG_VIDC_VENC_PARAM_SAR_WIDTH \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 48)

#define V4L2_CID_MPEG_VIDC_VENC_PARAM_SAR_HEIGHT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 49)

#define V4L2_CID_MPEG_VIDC_VIDEO_VQZIP_SEI	\
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 50)

enum v4l2_mpeg_vidc_video_vqzip_sei_enable {
	V4L2_CID_MPEG_VIDC_VIDEO_VQZIP_SEI_DISABLE	= 0,
	V4L2_CID_MPEG_VIDC_VIDEO_VQZIP_SEI_ENABLE	= 1
};

#define V4L2_CID_MPEG_VIDC_VENC_PARAM_LAYER_BITRATE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 51)

#define V4L2_CID_MPEG_VIDC_VIDEO_PRIORITY \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 52)

enum v4l2_mpeg_vidc_video_priority {
	V4L2_MPEG_VIDC_VIDEO_PRIORITY_REALTIME_ENABLE = 0,
	V4L2_MPEG_VIDC_VIDEO_PRIORITY_REALTIME_DISABLE = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_OPERATING_RATE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 53)

#define V4L2_CID_MPEG_VIDC_VIDEO_VENC_BITRATE_TYPE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 54)

enum v4l2_mpeg_vidc_video_venc_bitrate_type_enable {
	V4L2_CID_MPEG_VIDC_VIDEO_VENC_BITRATE_DISABLE	= 0,
	V4L2_CID_MPEG_VIDC_VIDEO_VENC_BITRATE_ENABLE	= 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_VPE_CSC \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 55)

enum v4l2_cid_mpeg_vidc_video_vpe_csc_type_enable {
	V4L2_CID_MPEG_VIDC_VIDEO_VPE_CSC_DISABLE  = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_VPE_CSC_ENABLE   = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_LOWLATENCY_MODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 56)

enum v4l2_mpeg_vidc_video_lowlatency_mode {
	V4L2_CID_MPEG_VIDC_VIDEO_LOWLATENCY_DISABLE     = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_LOWLATENCY_ENABLE      = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_BLUR_DIMENSIONS \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 57)

#define V4L2_CID_MPEG_VIDC_VIDEO_BLUR_WIDTH \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 58)

#define V4L2_CID_MPEG_VIDC_VIDEO_BLUR_HEIGHT \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 59)

#define V4L2_CID_MPEG_VIDC_VIDEO_COLOR_SPACE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 60)

#define V4L2_CID_MPEG_VIDC_VIDEO_FULL_RANGE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 61)

enum v4l2_cid_mpeg_vidc_video_full_range {
	V4L2_CID_MPEG_VIDC_VIDEO_FULL_RANGE_DISABLE = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_FULL_RANGE_ENABLE = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_TRANSFER_CHARS \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 62)

#define V4L2_CID_MPEG_VIDC_VIDEO_MATRIX_COEFFS \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 63)

#define V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_SIZE_TYPE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 64)

#define V4L2_CID_MPEG_VIDC_VIDEO_LAYER_ID \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 65)

#define V4L2_CID_MPEG_VIDC_VIDEO_VP9_PROFILE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 66)
enum v4l2_mpeg_vidc_video_vp9_profile {
	V4L2_MPEG_VIDC_VIDEO_VP9_PROFILE_UNUSED = 0,
	V4L2_MPEG_VIDC_VIDEO_VP9_PROFILE_P0 = 1,
	V4L2_MPEG_VIDC_VIDEO_VP9_PROFILE_P2_10 = 2,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_VP9_LEVEL \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 67)
enum v4l2_mpeg_vidc_video_vp9_level {
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_UNUSED = 0,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_1 = 1,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_11 = 2,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_2 = 3,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_21 = 4,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_3 = 5,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_31 = 6,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_4 = 7,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_41 = 8,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_5 = 9,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_51 = 10,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_6 = 11,
	V4L2_MPEG_VIDC_VIDEO_VP9_LEVEL_61 = 12,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_COLOR_SPACE_CAPS \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 68)
#define V4L2_CID_MPEG_VIDC_VIDEO_ROTATION_CAPS \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 69)

#define V4L2_CID_MPEG_VIDC_VIDEO_MB_ERROR_MAP_REPORTING \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 70)
#define V4L2_CID_MPEG_VIDC_VIDEO_CONTINUE_DATA_TRANSFER \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 71)

#define V4L2_CID_MPEG_VIDC_VIDEO_ALLOC_MODE_INPUT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 72)

#define V4L2_CID_MPEG_VIDC_VIDEO_FRAME_ASSEMBLY	\
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 73)
enum v4l2_mpeg_vidc_video_assembly {
	V4L2_MPEG_VIDC_FRAME_ASSEMBLY_DISABLE = 0,
	V4L2_MPEG_VIDC_FRAME_ASSEMBLY_ENABLE = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_H263_PROFILE\
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 74)
enum v4l2_mpeg_vidc_video_h263_profile {
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_BASELINE = 0,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_H320CODING	= 1,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_BACKWARDCOMPATIBLE = 2,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_ISWV2 = 3,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_ISWV3 = 4,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_HIGHCOMPRESSION = 5,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_INTERNET = 6,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_INTERLACE = 7,
	V4L2_MPEG_VIDC_VIDEO_H263_PROFILE_HIGHLATENCY = 8,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_OUTPUT_ORDER \
		(V4L2_CID_MPEG_MSM_VIDC_BASE+75)
enum v4l2_mpeg_vidc_video_output_order {
	V4L2_MPEG_VIDC_VIDEO_OUTPUT_ORDER_DISPLAY         = 0,
	V4L2_MPEG_VIDC_VIDEO_OUTPUT_ORDER_DECODE          = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_H264_TRANSFORM_8x8 \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 76)
enum v4l2_mpeg_vidc_video_h264_transform_8x8 {
	V4L2_MPEG_VIDC_VIDEO_H264_TRANSFORM_8x8_DISABLE = 0,
	V4L2_MPEG_VIDC_VIDEO_H264_TRANSFORM_8x8_ENABLE = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_QP_MASK \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 77)

#define V4L2_CID_MPEG_VIDEO_MIN_QP_PACKED \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 96)
#define V4L2_CID_MPEG_VIDEO_MAX_QP_PACKED \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 97)
#define V4L2_CID_MPEG_VIDC_VIDEO_ADAPTIVE_B \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 98)
#define V4L2_CID_MPEG_VIDC_VIDEO_I_FRAME_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 99)
#define V4L2_CID_MPEG_VIDC_VIDEO_P_FRAME_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 100)
#define V4L2_CID_MPEG_VIDC_VIDEO_B_FRAME_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 101)
#define V4L2_CID_MPEG_VIDC_VIDEO_I_FRAME_QP_MIN \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 102)
#define V4L2_CID_MPEG_VIDC_VIDEO_P_FRAME_QP_MIN \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 103)
#define V4L2_CID_MPEG_VIDC_VIDEO_B_FRAME_QP_MIN \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 104)
#define V4L2_CID_MPEG_VIDC_VIDEO_I_FRAME_QP_MAX \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 105)
#define V4L2_CID_MPEG_VIDC_VIDEO_P_FRAME_QP_MAX \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 106)
#define V4L2_CID_MPEG_VIDC_VIDEO_B_FRAME_QP_MAX \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 107)

#define V4L2_CID_MPEG_VIDC_VIDEO_DYN_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 108)

enum v4l2_mpeg_vidc_video_venc_iframesize_type {
	V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_SIZE_DEFAULT,
	V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_SIZE_MEDIUM,
	V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_SIZE_HUGE,
	V4L2_CID_MPEG_VIDC_VIDEO_IFRAME_SIZE_UNLIMITED,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_CONCEAL_COLOR_8BIT	\
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 109)
#define V4L2_CID_MPEG_VIDC_VIDEO_CONCEAL_COLOR_10BIT \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 110)

#define V4L2_CID_MPEG_VIDC_VIDEO_TME_PROFILE  \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 111)

enum v4l2_mpeg_vidc_video_tme_profile {
	V4L2_MPEG_VIDC_VIDEO_TME_PROFILE_0 = 0,
	V4L2_MPEG_VIDC_VIDEO_TME_PROFILE_1 = 1,
	V4L2_MPEG_VIDC_VIDEO_TME_PROFILE_2 = 2,
	V4L2_MPEG_VIDC_VIDEO_TME_PROFILE_3 = 3,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_TME_LEVEL \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 112)

enum v4l2_mpeg_vidc_video_tme_level {
	V4L2_MPEG_VIDC_VIDEO_TME_LEVEL_INTEGER = 0,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_TME_PAYLOAD_VERSION  \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 113)

#define V4L2_CID_MPEG_VIDC_VIDEO_VPE_CSC_CUSTOM_MATRIX \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 114)

#define V4L2_CID_MPEG_VIDC_VIDEO_FLIP (V4L2_CID_MPEG_MSM_VIDC_BASE + 115)
enum v4l2_mpeg_vidc_video_flip {
	V4L2_CID_MPEG_VIDC_VIDEO_FLIP_NONE = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_FLIP_HORI = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_FLIP_VERT = 2,
	V4L2_CID_MPEG_VIDC_VIDEO_FLIP_BOTH = 3,
};

/* HDR SEI INFO related control IDs and definitions*/
#define V4L2_MPEG_VIDC_VENC_HDR_INFO_ENABLED 1
#define V4L2_MPEG_VIDC_VENC_HDR_INFO_DISABLED 0

#define V4L2_CID_MPEG_VIDC_VENC_HDR_INFO \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 116)

#define  V4L2_CID_MPEG_VIDC_IMG_GRID_SIZE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 117)

#define V4L2_CID_MPEG_VIDC_COMPRESSION_QUALITY \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 118)

#define V4L2_CID_MPEG_VIDC_VIDEO_FRAME_RATE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 119)

#define V4L2_CID_MPEG_VIDC_VENC_BITRATE_SAVINGS \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 131)

#define V4L2_CID_MPEG_VIDC_VIDEO_HEVC_MAX_HIER_CODING_LAYER \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 120)
enum v4l2_mpeg_vidc_video_hevc_max_hier_coding_layer {
	V4L2_MPEG_VIDC_VIDEO_HEVC_MAX_HIER_CODING_LAYER_0 = 0,
	V4L2_MPEG_VIDC_VIDEO_HEVC_MAX_HIER_CODING_LAYER_1 = 1,
	V4L2_MPEG_VIDC_VIDEO_HEVC_MAX_HIER_CODING_LAYER_2 = 2,
	V4L2_MPEG_VIDC_VIDEO_HEVC_MAX_HIER_CODING_LAYER_3 = 3,
	V4L2_MPEG_VIDC_VIDEO_HEVC_MAX_HIER_CODING_LAYER_4 = 4,
	V4L2_MPEG_VIDC_VIDEO_HEVC_MAX_HIER_CODING_LAYER_5 = 5,
	V4L2_MPEG_VIDC_VIDEO_HEVC_MAX_HIER_CODING_LAYER_6 = 6,
};

#define V4L2_CID_MPEG_VIDC_VENC_CVP_DISABLE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 121)
#define V4L2_CID_MPEG_VIDC_VENC_NATIVE_RECORDER \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 122)

#define V4L2_CID_MPEG_VIDC_VENC_RC_TIMESTAMP_DISABLE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 123)

#define V4L2_CID_MPEG_VIDC_SUPERFRAME \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 124)

#define V4L2_CID_MPEG_VIDC_CAPTURE_FRAME_RATE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 125)

#define V4L2_CID_MPEG_VIDC_CVP_FRAME_RATE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 126)

#define V4L2_CID_MPEG_VIDC_VIDEO_ROI_TYPE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 127)
enum v4l2_mpeg_vidc_video_roi_type {
	V4L2_CID_MPEG_VIDC_VIDEO_ROI_TYPE_NONE = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_ROI_TYPE_2BIT = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_ROI_TYPE_2BYTE = 2,
};

#define V4L2_CID_MPEG_VIDC_SET_PERF_LEVEL \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 128)
enum v4l2_mpeg_vidc_perf_level {
	V4L2_CID_MPEG_VIDC_PERF_LEVEL_NOMINAL   = 0,
	V4L2_CID_MPEG_VIDC_PERF_LEVEL_PERFORMANCE       = 1,
	V4L2_CID_MPEG_VIDC_PERF_LEVEL_TURBO     = 2,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_LOWLATENCY_HINT \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 133)

#define V4L2_CID_MPEG_VIDC_VIDEO_AIR_MBS (V4L2_CID_MPEG_MSM_VIDC_BASE + 134)
#define V4L2_CID_MPEG_VIDC_VIDEO_AIR_REF (V4L2_CID_MPEG_MSM_VIDC_BASE + 135)
#define V4L2_CID_MPEG_VIDC_VIDEO_CIR_MBS (V4L2_CID_MPEG_MSM_VIDC_BASE + 136)

#define V4L2_CID_MPEG_VIDC_VIDEO_H264_VUI_TIMING_INFO \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 137)

#define V4L2_CID_MPEG_VIDEO_MULTI_SLICE_GOB \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 138)

#define V4L2_CID_MPEG_VIDC_VIDEO_H264_VUI_BITSTREAM_RESTRICT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 139)
enum v4l2_mpeg_vidc_video_h264_vui_bitstream_restrict {
	V4L2_MPEG_VIDC_VIDEO_H264_VUI_BITSTREAM_RESTRICT_DISABLED = 0,
	V4L2_MPEG_VIDC_VIDEO_H264_VUI_BITSTREAM_RESTRICT_ENABLED = 1
};

#define V4L2_CID_MPEG_VIDC_VIDEO_DEINTERLACE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 140)
enum v4l2_mpeg_vidc_video_deinterlace {
	V4L2_CID_MPEG_VIDC_VIDEO_DEINTERLACE_DISABLED = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_DEINTERLACE_ENABLED
};

#define V4L2_CID_MPEG_VIDC_VIDEO_MPEG4_TIME_RESOLUTION \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 141)

#define V4L2_CID_MPEG_VIDC_VIDEO_REQUEST_SEQ_HEADER \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 142)

#define V4L2_CID_MPEG_VIDC_VIDEO_RATE_CONTROL_TIMESTAMP_MODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 143)
enum v4l2_mpeg_vidc_video_rate_control_timestamp_mode {
	V4L2_MPEG_VIDC_VIDEO_RATE_CONTROL_TIMESTAMP_MODE_HONOR = 0,
	V4L2_MPEG_VIDC_VIDEO_RATE_CONTROL_TIMESTAMP_MODE_IGNORE = 1,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_ENABLE_INITIAL_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 144)
enum vl42_mpeg_vidc_video_enable_initial_qp {
	V4L2_CID_MPEG_VIDC_VIDEO_ENABLE_INITIAL_QP_IFRAME = 0x1,
	V4L2_CID_MPEG_VIDC_VIDEO_ENABLE_INITIAL_QP_PFRAME = 0x2,
	V4L2_CID_MPEG_VIDC_VIDEO_ENABLE_INITIAL_QP_BFRAME = 0x4,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_INITIAL_I_FRAME_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 145)

#define V4L2_CID_MPEG_VIDC_VIDEO_INITIAL_P_FRAME_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 146)

#define V4L2_CID_MPEG_VIDC_VIDEO_INITIAL_B_FRAME_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 147)

#define V4L2_CID_MPEG_VIDC_VIDEO_H264_NAL_SVC \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 148)

#define V4L2_CID_MPEG_VIDC_VIDEO_PERF_MODE	 \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 149)
enum v4l2_mpeg_vidc_video_perf_mode {
	V4L2_MPEG_VIDC_VIDEO_PERF_MAX_QUALITY = 1,
	V4L2_MPEG_VIDC_VIDEO_PERF_POWER_SAVE = 2
};

#define V4L2_CID_MPEG_VIDC_VIDEO_MBI_STATISTICS_MODE	\
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 150)

#define V4L2_CID_MPEG_VIDC_VIDEO_CONFIG_QP \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 151)

#define V4L2_CID_MPEG_VIDC_VIDEO_H264_PIC_ORDER_CNT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 152)

#define V4L2_CID_MPEG_VIDC_VIDEO_SCS_THRESHOLD \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 153)

#define V4L2_CID_MPEG_VIDC_VIDEO_MVC_BUFFER_LAYOUT \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 154)


#define V4L2_CID_MPEG_VIDC_VIDEO_SECURE_SCALING_THRESHOLD \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 155)

#define V4L2_CID_MPEG_VIDC_VIDEO_NON_SECURE_OUTPUT2 \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 156)

#define V4L2_CID_MPEG_VIDC_VIDEO_VP8_MIN_QP (V4L2_CID_MPEG_MSM_VIDC_BASE + 157)
#define V4L2_CID_MPEG_VIDC_VIDEO_VP8_MAX_QP (V4L2_CID_MPEG_MSM_VIDC_BASE + 158)

#define V4L2_CID_MPEG_VIDC_VIDEO_H263_LEVEL (V4L2_CID_MPEG_MSM_VIDC_BASE + 159)
enum v4l2_mpeg_vidc_video_h263_level {
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_1_0 = 0,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_2_0 = 1,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_3_0 = 2,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_4_0 = 3,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_4_5 = 4,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_5_0 = 5,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_6_0 = 6,
	V4L2_MPEG_VIDC_VIDEO_H263_LEVEL_7_0 = 7,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_POST_LOOP_DEBLOCKER_MODE \
		(V4L2_CID_MPEG_MSM_VIDC_BASE + 160)


#define V4L2_CID_MPEG_VIDC_VIDEO_DIVX_FORMAT (V4L2_CID_MPEG_MSM_VIDC_BASE+161)

enum v4l2_mpeg_vidc_video_divx_format_type {
		V4L2_MPEG_VIDC_VIDEO_DIVX_FORMAT_4 = 0,
		V4L2_MPEG_VIDC_VIDEO_DIVX_FORMAT_5 = 1,
		V4L2_MPEG_VIDC_VIDEO_DIVX_FORMAT_6 = 2,
};

#define V4L2_CID_MPEG_VIDC_IMG_GRID_DIMENSION \
	(V4L2_CID_MPEG_MSM_VIDC_BASE+163)

#define V4L2_CID_MPEG_VIDC_VIDEO_FRAME_QP \
	(V4L2_CID_MPEG_MSM_VIDC_BASE+164)

#define  \
V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_MODE \
	(V4L2_CID_MPEG_MSM_VIDC_BASE+165)
enum v4l2_mpeg_vidc_video_intra_refresh_mode {
	V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_NONE = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_CYCLIC = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_RANDOMMODE = 2,
	V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_ADAPTIVE = 3,
	V4L2_CID_MPEG_VIDC_VIDEO_INTRA_REFRESH_CYCLIC_ADAPTIVE = 4,
};

#define V4L2_CID_MPEG_VIDC_VIDEO_IR_MBS (V4L2_CID_MPEG_MSM_VIDC_BASE+166)

#define V4L2_CID_MPEG_VIDC_ENABLE_ONLY_BASE_LAYER_IR \
	(V4L2_CID_MPEG_MSM_VIDC_BASE + 167)

enum v4l2_mpeg_vidc_video_mbi_statistics_mode {
	V4L2_CID_MPEG_VIDC_VIDEO_MBI_MODE_DEFAULT = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_MBI_MODE_1 = 1,
	V4L2_CID_MPEG_VIDC_VIDEO_MBI_MODE_2 = 2,
	V4L2_CID_MPEG_VIDC_VIDEO_MBI_MODE_3 = 3,
};

enum vl42_mpeg_vidc_video_h264_svc_nal {
	V4L2_CID_MPEG_VIDC_VIDEO_H264_NAL_SVC_DISABLED = 0,
	V4L2_CID_MPEG_VIDC_VIDEO_H264_NAL_SVC_ENABLED = 1,
};

enum v4l2_mpeg_vidc_video_h264_vui_timing_info {
	V4L2_MPEG_VIDC_VIDEO_H264_VUI_TIMING_INFO_DISABLED = 0,
	V4L2_MPEG_VIDC_VIDEO_H264_VUI_TIMING_INFO_ENABLED = 1
};

#endif /* __MSM_VIDC_V4L2_COMPAT_H__ */
